# yaml-language-server: $schema=https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/1.4.0/tools/projmgr/schemas/cdefault.schema.json

default:
  compiler: AC6

  misc:
    - for-compiler: GCC
      C-CPP:
        - -gdwarf-3
      C:
        - -std=gnu11
      Link:
        - --specs=nosys.specs

    - for-compiler: AC6
      C-CPP:
        - -Wno-macro-redefined
        - -Wno-pragma-pack
        - -Wno-parentheses-equality
      C:
        - -std=gnu11
      Link:
        - --entry=Reset_Handler
        - --info summarysizes

